### ISSUE TITLE
Has there been a change to SteamAPI

### ISSUE THREAD

**Issue by TacoCub** [TrainDoctor/PZModScraper#1]
Hello,
I tried using this recently to save myself many hours of copy/pasting and im getting an error due to the steam web api.

```
from steam.webapi import WebAPI
ModuleNotFoundError: No module named 'steam.webapi'
```

Not sure if this repo is supported, but figured I would inquire.  Im investigating some API Wrappers ive found to resolve the issue.

Edit:
- [x] Add steam module to readme
- [ ] Add a requirements.txt file

**Comment by TrainDoctor** [comment]
It looks like I never included that the "steam" module made by ValvePython is also needed. I'll look into making a requirements.txt and adding a part to the readme since I forgot to include this detail originally, whoops!

**Comment by TrainDoctor** [comment]
I've added the steam module to the dependencies in the readme. I might get around to a requirements.txt but it's taking a bit more effort than I expected.

**Comment by TrainDoctor** [comment]
Okay, used pigar and generated a requirements.txt! Hopefully this should avoid any issues in future. Thanks for the report.
